### PR TITLE
Query string plus are decoded as whitespaces

### PR DESCRIPTION
**Pull request by FinchPowers**

### CODE REVIEW

**Comment by jeremybarnes** [comment]
Funny, I wrote exactly the same patch

I added another test

BOOST_AUTO_TEST_CASE(test_http_header_query_parser_g8)
{
    // + and space interchanged
    auto parser = generateParser("/?foo=+ hello +");
    testQueryParam(parser, "foo", "  hello  ");
}

**Comment by FinchPowers** [comment]
This test is not correct. It should be

    testQueryParam(parser, "foo", "  hello  ");

(With double whitespaces)

**Comment by jeremybarnes** [comment]
Believe it or not, that was how I wrote it.  I have no idea how the space got lost in the copying and pasting.

**Comment by FinchPowers** [comment]
Test testQueryParam(parser, "foo", "  hello  ");

**Comment by FinchPowers** [comment]
Confirmed, github ate the double white space.

**Pull request merged**
