### PR TITLE
Added support for Date request parameters

### PR DESCRIPTION
**Pull request by wsourdeau**

### CODE REVIEW

**Comment by jeremybarnes** [comment]
I'm not 100% clear on why this is needed.  Previously I just passed dates as quoted JSON strings (with the quotes URL encoded).  What does this make possible?

**Comment by wsourdeau** [comment]
I did not know that technique, but what this code enables is the passing of dates in iso 8601 format (not requiring any quoting or escaping). Previously, this would fail with this exception:
"date istream parsing doesn't work yet"

I suppose the choice is now between the quoted json format and the unquoted 8601 format.... Do you have a preference?

**Comment by jeremybarnes** [comment]
+1 anyway

**Comment by wsourdeau** [comment]
Apparentluy merged already

**Pull request closed without merging**
